# analysis_options.yaml

include: package:flutter_lints/flutter.yaml # This line is usually present by default

linter:
  rules:
    # To enable prefer_const_constructors (this is usually enabled by default with flutter_lints)
    - prefer_const_constructors

    # To disable prefer_const_constructors
    # prefer_const_constructors: false