# Uncomment this line to define a global platform for your project
platform :ios, '12.0' # Or your desired minimum iOS version

# Flutter setting, don't change these unless you know what you're doing.
flutter_application_path = File.expand_path('../.symlinks/flutter/ios', __FILE__)
load File.join(flutter_application_path, 'Flutter', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods_into_project
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
        config.build_settings[GCC_PREPROCESSOR_DEFINITIONS] ||= [
            '$(inherited)',
            'AUDIO_SESSION_MICROPHONE=0',
        ]
    end
  end
end